/** @type {import('tailwindcss').Config} */

// Charte « Ciel produit » (docs/v1/maquettes-ciel/FONDATIONS.md) : Tailwind ne consomme QUE les tokens
// --jb-* (src/styles/tokens.css). La palette par défaut de Tailwind est remplacée,
// pas étendue : une classe `bg-blue-500` ne compile même pas.
const token = (name) => `var(--jb-${name})`;

module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      inherit: 'inherit',
      paper: token('paper'),
      surface: token('surface'),
      'surface-2': token('surface-2'),
      ink: token('ink'),
      'ink-2': token('ink-2'),
      'ink-3': token('ink-3'),
      'ink-4': token('ink-4'),
      line: token('line'),
      'line-field': token('line-field'),
      'line-strong': token('line-strong'),
      'line-active': token('line-active'),
      primary: token('primary'),
      'primary-strong': token('primary-strong'),
      'primary-fill': token('primary-fill'),
      'primary-fill-hover': token('primary-fill-hover'),
      'on-primary': token('on-primary'),
      'on-primary-muted': token('on-primary-muted'),
      'on-lit-white': token('on-lit-white'),
      brand: token('brand'),
      inverse: token('inverse'),
      'on-inverse': token('on-inverse'),
      'on-inverse-muted': token('on-inverse-muted'),
      night: token('night'),
      'night-2': token('night-2'),
      'on-night': token('on-night'),
      'on-night-muted': token('on-night-muted'),
      tint: {
        50: token('tint-50'),
        100: token('tint-100'),
        200: token('tint-200'),
        300: token('tint-300'),
        400: token('tint-400'),
        500: token('tint-500'),
        800: token('tint-800'),
        900: token('tint-900'),
      },
      ok: token('ok'),
      'ok-bg': token('ok-bg'),
      'ok-dot': token('ok-dot'),
      warn: token('warn'),
      'warn-dot': token('warn-dot'),
      'warn-bg': token('warn-bg'),
      err: token('err'),
      'err-bg': token('err-bg'),
      'err-line': token('err-line'),
      'err-fill': token('err-fill'),
      scrim: token('scrim'),
      lit: {
        green: token('lit-green'),
        violet: token('lit-violet'),
        gold: token('lit-gold'),
        'gold-text': token('lit-gold-text'),
        red: token('lit-red'),
        rose: token('lit-rose'),
        'rose-text': token('lit-rose-text'),
        white: token('lit-white'),
      },
    },
    fontFamily: {
      // Libre Franklin : toute l'interface. Source Serif 4 : la Parole, les citations bibliques, le logotype.
      serif: ['var(--font-serif)', 'Georgia', 'serif'],
      sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
    },
    // Échelle « Ciel produit » (WEB-Design-System) : le nom est la taille en px à 100 %,
    // la valeur en rem pour suivre le réglage « taille du texte » du navigateur (WCAG 1.4.4).
    fontSize: {
      11: ['0.6875rem', { lineHeight: '1rem' }],
      12: ['0.75rem', { lineHeight: '1rem' }],
      13: ['0.8125rem', { lineHeight: '1.125rem' }],
      14: ['0.875rem', { lineHeight: '1.25rem' }],
      15: ['0.9375rem', { lineHeight: '1.375rem' }],
      16: ['1rem', { lineHeight: '1.5rem' }],
      17: ['1.0625rem', { lineHeight: '1.5rem' }],
      18: ['1.125rem', { lineHeight: '1.75rem' }],
      19: ['1.1875rem', { lineHeight: '1.875rem' }],
      20: ['1.25rem', { lineHeight: '1.75rem' }],
      22: ['1.375rem', { lineHeight: '1.75rem' }],
      24: ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.01em' }],
      28: ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.01em' }],
      30: ['1.875rem', { lineHeight: '2.625rem' }],
      32: ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.01em' }],
      36: ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.01em' }],
      40: ['2.5rem', { lineHeight: '3rem', letterSpacing: '-0.015em' }],
      48: ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.02em' }],
      56: ['3.5rem', { lineHeight: '4rem', letterSpacing: '-0.02em' }],
      // Anciens noms (écrans non migrés), rabattus sur l'échelle Ciel. À ne plus employer.
      meta: ['0.75rem', { lineHeight: '1rem' }],
      xs: ['0.8125rem', { lineHeight: '1.125rem' }],
      sm: ['0.875rem', { lineHeight: '1.25rem' }],
      base: ['0.9375rem', { lineHeight: '1.375rem' }],
      body: ['1rem', { lineHeight: '1.5rem' }],
      lead: ['1.125rem', { lineHeight: '1.75rem' }],
      h4: ['1.25rem', { lineHeight: '1.75rem' }],
      h3: ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.01em' }],
      h2: ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.01em' }],
      title: ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.01em' }],
      h1: ['2.5rem', { lineHeight: '3rem', letterSpacing: '-0.015em' }],
      display: ['3.5rem', { lineHeight: '4rem', letterSpacing: '-0.02em' }],
    },
    // Rayons : 3 pastille de légende, 6 case, 8 petit, 10 nav, 12 champ et bouton, 14 tuile de jour, 16 carte, 999 pilule.
    borderRadius: {
      none: '0',
      DEFAULT: '10px',
      sm: '6px',
      md: '8px',
      lg: '12px',
      xl: '16px',
      3: '3px',
      4: '4px',
      5: '5px',
      6: '6px',
      8: '8px',
      9: '9px',
      10: '10px',
      12: '12px',
      14: '14px',
      16: '16px',
      full: '9999px',
    },
    extend: {
      maxWidth: { reading: '68ch', parole: '680px', content: '1120px', public: '1200px' },
      spacing: { 5.5: '22px', 13: '52px', 15: '60px', 18: '72px', 66: '264px', 68: '272px' },
      boxShadow: {
        card: 'var(--jb-shadow-card)',
        menu: 'var(--jb-shadow-menu)',
        // Ancien nom : modale et tiroir prennent l'ombre de menu.
        modal: 'var(--jb-shadow-menu)',
      },
      borderWidth: { 3: '3px', 1.5: '1.5px' },
      keyframes: { 'jb-spin': { to: { transform: 'rotate(360deg)' } } },
      animation: { 'jb-spin': 'jb-spin 1s linear infinite' },
    },
  },
  plugins: [],
};
